cache:
    physbits: 40 # number of bits in physical address
    size: 16777216 # cache size in bytes
    bsize: 8 # block or line size
    assoc: 16 # associativity
    cin: 12 # maximum input capacitance in terms of lambda

# SRAM cell model parameters
# lambda = min feature size = 0.5*technology node
cell_model:
    cin: 8 # wordline transistor input capacitance in terms of lambda
    w: 16 # width (along wordline) in lambda
    h: 40 # height (along bitline) in lambda

# local wire parameters
wire_model:
    pitch: 0.14 # width + spacing in um
    width: 0.07 # spacing in um
    height: 0.26 # from next lower layer in um
    thickness: 0.125 # vertical dimension thickness in um

# global wire parameters
global_wire_model:
    eperl: 0.08 # energy/bit/mm in pJ/mm, assuming a activity factor of 0.25
    tperl: 0.3 # delay per mm in ns/mm
